apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2
  selector:
    app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - image: hello-kube:latest
          name: hello-container-name
          ports:
            - containerPort: 3000
