apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
data:
  MYSQL_ROOT_USER: "cm9vdAo=" # cli: echo 'root' | base64
  MYSQL_ROOT_PASSWORD: "cGFzc3dvcmQxMjMK" # cli: echo 'password123' | base64
