apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-testing-ns
  namespace: testing
spec:
  containers:
    - image: hello-kube:latest
      name: hello-cute-kube
      ports:
        - containerPort: 3000
          protocol: TCP
